[package]
name = "sadramoh/universal_lib_go"
version = "0.0.1-alpha.3"
description = "Universal go library"
readme = "README.md"

[[module]]
name = "universal_lib_go"
source = "universal_lib_go.wasm"
abi = "wasi"

[module.bindings]
wai-version = "0.1.0"
exports = "universal-lib-go.wai"
